"""
rule_proposer.py — Pattern-to-Rule Proposer

Purpose:
  Reads output/patterns.json (generated by pattern_miner)
  Finds validated/preliminary patterns with negative direction and high edge
  Writes output/proposed_rules.json with actionable proposals

  Proposals can be approved via Telegram /approve_rule <id> command,
  which updates data/mini_scanner_rules.json automatically.

Key rules:
  - Only surface patterns with edge >= 10pp AND n >= 10
  - Skip patterns already active in mini_scanner_rules.json kill_patterns
  - Mark previously approved proposals as "already_active" (not duplicated)
  - Status lifecycle: pending -> approved / rejected / already_active

Output schema:
  {
    "schema_version": 1,
    "generated_at": "...",
    "total_proposals": N,
    "pending_count": N,
    "proposals": [ {...} ]
  }

FIX C-02 (Apr 21 2026):
  Replaced bare-relative paths (PATTERNS_PATH / PROPOSED_RULES_PATH /
  MINI_RULES_PATH) with _HERE/_ROOT absolute paths matching the
  pattern used by every other scanner module. The relative paths
  resolved to scanner/output/ and scanner/data/ when main.py ran
  with cwd=scanner/ (as eod_master.yml step 7 does), causing all
  reads to miss and all writes to land in disposable locations.

FIX C-04 (Apr 21 2026):
  approve_proposal() and reject_proposal() now return dicts instead
  of (bool, str) tuples. telegram_bot._respond_approve_rule calls
  .get() on the result, which raised AttributeError on every call.
  New shape: {success, action, target, message, error, kill_rule_id}
"""

import glob
import json
import os
from datetime import datetime, timedelta
from pathlib import Path

# prop_007 thresholds — imported lazily inside helpers to keep
# rule_proposer.py runnable as a standalone script (PYTHONPATH may
# not include scanner/ during local dev). Constants:
#   BOOST_DEMOTION_PROPOSAL_PERSIST_DAYS  = 3
#   BOOST_DEMOTION_PROPOSAL_AUTO_EXPIRE_DAYS = 7

# ── PATHS (C-02 FIX: absolute paths via _HERE/_ROOT) ─────────
_HERE   = os.path.dirname(os.path.abspath(__file__))
_ROOT   = os.path.dirname(_HERE)
_OUTPUT = os.path.join(_ROOT, 'output')
_DATA   = os.path.join(_ROOT, 'data')

PATTERNS_PATH       = os.path.join(_OUTPUT, 'patterns.json')
PROPOSED_RULES_PATH = os.path.join(_OUTPUT, 'proposed_rules.json')
MINI_RULES_PATH     = os.path.join(_DATA,   'mini_scanner_rules.json')

SCHEMA_VERSION = 1

# Thresholds for promoting patterns to proposals
MIN_N_FOR_PROPOSAL = 10           # minimum sample size
MIN_EDGE_PP = 10                   # minimum edge (percentage points)
MIN_EDGE_PP_KILL = 15              # minimum edge for KILL (stricter)


def _load_json(path, default=None):
    """Load JSON file with safe fallback."""
    if not os.path.exists(path):
        return default
    try:
        with open(path, 'r') as f:
            return json.load(f)
    except (json.JSONDecodeError, FileNotFoundError):
        print(f"[rule_proposer] Warning: {path} corrupt, using default")
        return default


def _save_json(path, data):
    """Save JSON atomically."""
    # Ensure parent directory exists (defensive — should always exist)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp_path = path + ".tmp"
    with open(tmp_path, 'w') as f:
        json.dump(data, f, indent=2)
    os.replace(tmp_path, path)


def _get_active_kill_patterns():
    """Read current kill_patterns from mini_scanner_rules.json."""
    rules = _load_json(MINI_RULES_PATH, default={})
    return rules.get('kill_patterns', [])


def _pattern_matches_active_rule(pattern, active_kills):
    """Check if a pattern is already an active kill rule."""
    features = pattern.get('features', {})
    target_signal = features.get('signal')
    target_sector = features.get('sector')

    if not target_signal or not target_sector:
        return False

    for kill in active_kills:
        if (kill.get('signal') == target_signal and
                kill.get('sector') == target_sector):
            return True
    return False


def _load_existing_proposals():
    """Load existing proposed_rules.json to preserve history."""
    data = _load_json(PROPOSED_RULES_PATH, default={
        "schema_version": SCHEMA_VERSION,
        "proposals": []
    })
    return data.get('proposals', [])


def _generate_proposal_id(existing_proposals):
    """Generate next prop_XXX ID."""
    existing_ids = [
        p.get('id', '') for p in existing_proposals
        if p.get('id', '').startswith('prop_')
    ]
    max_num = 0
    for pid in existing_ids:
        try:
            num = int(pid.replace('prop_', ''))
            max_num = max(max_num, num)
        except ValueError:
            continue
    return f"prop_{str(max_num + 1).zfill(3)}"


def _find_matching_proposal(pattern_id, existing_proposals):
    """Check if a proposal for this pattern already exists."""
    for p in existing_proposals:
        if p.get('pattern_id') == pattern_id:
            return p
    return None


def _classify_action(pattern):
    """
    Decide what action this pattern should propose.

    - kill: n>=10, edge<=-15pp, direction=negative
    - warn: n>=10, edge<=-10pp, direction=negative
    - boost: n>=10, edge>=15pp, direction=positive (future use)
    """
    n = pattern.get('n_resolved', 0)
    edge = pattern.get('edge_pct', 0) or 0
    direction = pattern.get('direction', '')

    if n < MIN_N_FOR_PROPOSAL:
        return None

    if direction == 'negative':
        if edge <= -MIN_EDGE_PP_KILL:
            return 'kill'
        elif edge <= -MIN_EDGE_PP:
            return 'warn'

    # Positive direction boost patterns — not acted upon yet, Phase 4
    # elif direction == 'positive' and edge >= MIN_EDGE_PP_KILL:
    #     return 'boost'

    return None


def _build_proposal(pattern, existing_proposals, active_kills):
    """Convert a pattern into a proposal record."""
    action = _classify_action(pattern)
    if action is None:
        return None

    features = pattern.get('features', {})
    target_signal = features.get('signal')
    target_sector = features.get('sector')

    # Need at least signal OR sector feature to be actionable
    if not target_signal and not target_sector:
        return None

    pattern_id = pattern.get('id', '')

    # Check if proposal already exists for this pattern
    existing = _find_matching_proposal(pattern_id, existing_proposals)

    if existing:
        # Already proposed — update evidence with latest numbers, keep status
        existing['evidence'] = {
            'wr': pattern.get('wr', 0),
            'n': pattern.get('n_resolved', 0),
            'avg_pnl': pattern.get('avg_pnl', 0),
            'avg_mae': pattern.get('avg_mae', 0),
            'avg_mfe': pattern.get('avg_mfe', 0),
            'edge_pp': pattern.get('edge_pct', 0),
            'tier': pattern.get('tier', ''),
            'baseline_type': pattern.get('baseline_type', ''),
            'baseline_wr': pattern.get('baseline_wr', 0)
        }
        existing['last_updated'] = datetime.utcnow().isoformat() + "Z"

        # If this was pending and is now active in rules, mark it
        if existing.get('status') == 'pending' and _pattern_matches_active_rule(pattern, active_kills):
            existing['status'] = 'already_active'
            existing['approved_date'] = datetime.utcnow().isoformat() + "Z"
            existing['approved_by'] = 'auto_sync_kill_patterns'

        return existing

    # New proposal
    prop_id = _generate_proposal_id(existing_proposals)

    # Check if this matches an already-active kill rule (shipped manually tonight)
    if _pattern_matches_active_rule(pattern, active_kills):
        status = 'already_active'
    else:
        status = 'pending'

    proposal = {
        'id': prop_id,
        'pattern_id': pattern_id,
        'action': action,
        'target_signal': target_signal,
        'target_sector': target_sector,
        'evidence': {
            'wr': pattern.get('wr', 0),
            'n': pattern.get('n_resolved', 0),
            'avg_pnl': pattern.get('avg_pnl', 0),
            'avg_mae': pattern.get('avg_mae', 0),
            'avg_mfe': pattern.get('avg_mfe', 0),
            'edge_pp': pattern.get('edge_pct', 0),
            'tier': pattern.get('tier', ''),
            'baseline_type': pattern.get('baseline_type', ''),
            'baseline_wr': pattern.get('baseline_wr', 0)
        },
        'status': status,
        'proposed_date': datetime.utcnow().isoformat() + "Z",
        'approved_date': datetime.utcnow().isoformat() + "Z" if status == 'already_active' else None,
        'approved_by': 'auto_sync_kill_patterns' if status == 'already_active' else None,
        'rejected_date': None,
        'rejected_reason': None,
        'last_updated': datetime.utcnow().isoformat() + "Z",
        'insight': pattern.get('insight', '')
    }

    return proposal


# =====================================================================
# prop_007 — boost demotion proposal generation + approval
# =====================================================================
#
# Reads bridge_state_history/<date>_EOD.json files (written by
# composers/eod.py with LE-06 pattern_updates). When a boost_pattern
# appears as kind="boost_demotion_warning" on EVERY one of the most
# recent N EOD days (set INTERSECTION across days, not union), generate
# a demote_boost proposal.
#
# Date-source discipline: rule_proposer.py uses datetime.utcnow()
# everywhere; bridge_state_history filenames use composer's market_date
# which comes from _today_ist() (Asia/Kolkata). To avoid UTC/IST drift
# at midnight boundaries, we glob filenames and sort lexicographically
# (ISO dates sort correctly). NEVER compute "today minus N days"
# arithmetic.

_BRIDGE_HISTORY_DIR = os.path.join(_OUTPUT, 'bridge_state_history')
_EOD_FILE_GLOB = '*_EOD.json'
_BOOST_WARNING_KIND = 'boost_demotion_warning'


def _read_recent_eod_pattern_updates(n_days):
    """Read most-recent N bridge_state_history/*_EOD.json files.

    Returns list of (date_str, pattern_updates_list) tuples ordered most-
    recent-first. Defensive: missing dir / missing files / malformed JSON /
    missing summary key all silently skip; returns [] on full failure.
    """
    if not os.path.isdir(_BRIDGE_HISTORY_DIR):
        return []
    pattern = os.path.join(_BRIDGE_HISTORY_DIR, _EOD_FILE_GLOB)
    files = sorted(glob.glob(pattern), reverse=True)[:n_days]
    out = []
    for path in files:
        # Extract date prefix from filename: "<date>_EOD.json"
        fname = os.path.basename(path)
        date_str = fname.split('_EOD.json')[0] if '_EOD.json' in fname else ''
        try:
            with open(path, 'r') as f:
                state = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(state, dict):
            continue
        summary = state.get('summary')
        if not isinstance(summary, dict):
            continue
        pu = summary.get('pattern_updates')
        if not isinstance(pu, list):
            continue
        out.append((date_str, pu))
    return out


def _detect_boost_demotion_candidates(eod_history):
    """Find pattern_ids appearing as kind=boost_demotion_warning on
    EVERY one of the eod_history days (set INTERSECTION, not union).

    eod_history shape: list of (date_str, pattern_updates_list) tuples.

    Returns list of candidate dicts with most-recent-day stats:
      pattern_id, streak_days, latest_window_wr, latest_window_wins,
      latest_window_losses, latest_threshold_wr, latest_signal,
      latest_sector, latest_regime, latest_current_tier
    """
    if not eod_history or len(eod_history) < 1:
        return []

    # Per-day: set of pattern_ids that fired the warning kind that day
    per_day_ids = []
    for _, updates in eod_history:
        ids = set()
        for u in updates:
            if not isinstance(u, dict):
                continue
            if u.get('kind') != _BOOST_WARNING_KIND:
                continue
            pid = u.get('pattern_id')
            if isinstance(pid, str) and pid:
                ids.add(pid)
        per_day_ids.append(ids)

    # Streak qualification: pattern_id must appear in ALL N days
    streak_ids = set.intersection(*per_day_ids) if per_day_ids else set()
    if not streak_ids:
        return []

    # Pull latest-day stats for each streak pattern_id
    # (eod_history[0] is most recent because sorted reverse=True)
    latest_updates = eod_history[0][1]
    latest_by_pid = {}
    for u in latest_updates:
        if not isinstance(u, dict):
            continue
        if u.get('kind') != _BOOST_WARNING_KIND:
            continue
        pid = u.get('pattern_id')
        if pid in streak_ids:
            latest_by_pid[pid] = u

    out = []
    streak_n = len(eod_history)
    for pid in sorted(streak_ids):
        u = latest_by_pid.get(pid) or {}
        out.append({
            'pattern_id':            pid,
            'streak_days':           streak_n,
            'latest_window_wr':      u.get('window_wr'),
            'latest_window_wins':    u.get('window_wins'),
            'latest_window_losses':  u.get('window_losses'),
            'latest_threshold_wr':   u.get('threshold_wr'),
            'latest_signal':         u.get('signal'),
            'latest_sector':         u.get('sector'),
            'latest_regime':         u.get('regime'),
            'latest_current_tier':   u.get('current_tier'),
        })
    return out


def _build_demote_boost_proposal(candidate, prop_id):
    """Construct one demote_boost proposal entry per S2 schema.

    13 evidence sub-fields plus top-level shape. Insight string format:
      "Boost pattern {id} ({signal} × {sector_label} × {regime_label})
      below {floor}% WR floor {streak} days running; latest window
      {wr}% ({wins}/{w+l})"
    """
    pid = candidate['pattern_id']
    signal = candidate.get('latest_signal') or '?'
    sector = candidate.get('latest_sector')
    regime = candidate.get('latest_regime')
    sector_label = 'any' if sector in (None, 'ANY') else sector
    regime_label = 'any' if regime in (None, 'ANY') else regime

    wr = candidate.get('latest_window_wr')
    wins = candidate.get('latest_window_wins')
    losses = candidate.get('latest_window_losses')
    threshold = candidate.get('latest_threshold_wr') or 0.70
    streak = candidate.get('streak_days') or 0

    wr_pct = int(round((wr or 0) * 100))
    floor_pct = int(round(threshold * 100))
    wl_total = (wins or 0) + (losses or 0)

    insight = (
        f"Boost pattern {pid} ({signal} × {sector_label} × "
        f"{regime_label}) below {floor_pct}% WR floor {streak} days "
        f"running; latest window {wr_pct}% ({wins}/{wl_total})"
    )

    now = datetime.utcnow().isoformat() + "Z"
    return {
        'id':              prop_id,
        'pattern_id':      pid,
        'action':          'demote_boost',
        'target_signal':   signal,
        'target_sector':   sector,
        'target_regime':   regime,
        'evidence': {
            'warning_streak_days':  streak,
            'latest_window_wr':     wr,
            'latest_window_wins':   wins,
            'latest_window_losses': losses,
            'threshold_wr':         threshold,
            'current_tier':         candidate.get('latest_current_tier'),
        },
        'status':          'pending',
        'proposed_date':   now,
        'approved_date':   None,
        'approved_by':     None,
        'rejected_date':   None,
        'rejected_reason': None,
        'last_updated':    now,
        'insight':         insight,
    }


def _generate_boost_demotion_proposals(existing_proposals, candidates):
    """For each candidate, build a demote_boost entry per S2 schema.

    Dedup via _find_matching_proposal: skip if any matching pattern_id
    already exists in existing_proposals (consistent with kill/warn
    dedup behavior — note this also blocks re-proposal after rejection,
    same as existing logic).
    """
    out = []
    working = list(existing_proposals)
    for cand in candidates:
        pid = cand['pattern_id']
        if _find_matching_proposal(pid, working):
            # Same dedup semantics as kill/warn: any existing entry
            # with this pattern_id (pending / approved / rejected /
            # already_active) blocks re-proposal.
            continue
        new_id = _generate_proposal_id(working)
        proposal = _build_demote_boost_proposal(cand, new_id)
        out.append(proposal)
        working.append(proposal)
    return out


def _expire_stale_demote_boost_proposals(existing_proposals,
                                         expire_days):
    """Mark pending demote_boost proposals older than expire_days as
    'expired'. In-place mutation of the list.

    Deliberately scoped to action='demote_boost' only. kill/warn
    proposals do NOT auto-expire — that is existing production
    behavior, intentionally preserved. A future reader who wants to
    add auto-expire to kill/warn must do so as a separate scoped
    decision; do not "fix" this by extending the filter here.
    """
    cutoff = datetime.utcnow() - timedelta(days=expire_days)
    expired_count = 0
    for p in existing_proposals:
        if p.get('action') != 'demote_boost':
            continue
        if p.get('status') != 'pending':
            continue
        proposed = p.get('proposed_date')
        if not isinstance(proposed, str):
            continue
        try:
            # Parse trailing-Z UTC ISO format
            proposed_dt = datetime.fromisoformat(
                proposed.rstrip('Z'))
        except ValueError:
            continue
        if proposed_dt < cutoff:
            p['status'] = 'expired'
            p['last_updated'] = datetime.utcnow().isoformat() + "Z"
            expired_count += 1
    return expired_count


def generate_proposals():
    """
    Main entry point.
    Reads patterns.json, generates proposals, writes proposed_rules.json.
    Returns summary dict.
    """
    print("[rule_proposer] Starting proposal generation...")
    print(f"[rule_proposer] PATTERNS_PATH       = {PATTERNS_PATH}")
    print(f"[rule_proposer] PROPOSED_RULES_PATH = {PROPOSED_RULES_PATH}")
    print(f"[rule_proposer] MINI_RULES_PATH     = {MINI_RULES_PATH}")

    # Load patterns
    patterns_data = _load_json(PATTERNS_PATH, default={"patterns": []})
    patterns = patterns_data.get('patterns', [])
    print(f"[rule_proposer] Loaded {len(patterns)} patterns from {PATTERNS_PATH}")

    if not patterns:
        print("[rule_proposer] No patterns found. Skipping.")
        return {"total": 0, "pending": 0, "already_active": 0}

    # Load existing proposals (preserve history)
    existing_proposals = _load_existing_proposals()
    print(f"[rule_proposer] Found {len(existing_proposals)} existing proposals")

    # prop_007: auto-expire stale pending demote_boost proposals (>7 days).
    # Lazy import to keep this module runnable without scanner/ on PYTHONPATH.
    try:
        from scanner.bridge.rules.thresholds import (
            BOOST_DEMOTION_PROPOSAL_AUTO_EXPIRE_DAYS,
        )
        n_expired = _expire_stale_demote_boost_proposals(
            existing_proposals,
            BOOST_DEMOTION_PROPOSAL_AUTO_EXPIRE_DAYS,
        )
        if n_expired > 0:
            print(f"[rule_proposer] Auto-expired {n_expired} stale "
                  "pending demote_boost proposals")
    except ImportError:
        pass

    # Load active kill rules
    active_kills = _get_active_kill_patterns()
    print(f"[rule_proposer] Found {len(active_kills)} active kill rules")

    # Process each pattern
    proposals = []
    new_count = 0
    updated_count = 0
    already_active_count = 0

    for pattern in patterns:
        proposal = _build_proposal(pattern, proposals + existing_proposals, active_kills)
        if proposal is None:
            continue

        # Check if it's in existing (updated) or new
        matching = _find_matching_proposal(
            proposal.get('pattern_id'), existing_proposals
        )
        if matching:
            updated_count += 1
        else:
            new_count += 1

        if proposal.get('status') == 'already_active':
            already_active_count += 1

        proposals.append(proposal)

    # Preserve existing proposals that weren't in this pattern set (maybe pattern disappeared as data shifted)
    existing_ids_in_current = {p.get('pattern_id') for p in proposals}
    for old_prop in existing_proposals:
        if old_prop.get('pattern_id') not in existing_ids_in_current:
            # Pattern no longer appears in latest patterns.json — mark stale but keep
            old_prop['status_note'] = 'pattern_no_longer_surfaced'
            old_prop['last_updated'] = datetime.utcnow().isoformat() + "Z"
            proposals.append(old_prop)

    # prop_007: generate boost demotion proposals from LE-06 warning
    # streaks. Reads bridge_state_history/<date>_EOD.json — see helper
    # comments for date-source discipline (filename glob, no UTC/IST
    # arithmetic). Dedup via _find_matching_proposal across the full
    # current proposals list (= patterns-loop output + preserved old).
    try:
        from scanner.bridge.rules.thresholds import (
            BOOST_DEMOTION_PROPOSAL_PERSIST_DAYS,
        )
        eod_history = _read_recent_eod_pattern_updates(
            BOOST_DEMOTION_PROPOSAL_PERSIST_DAYS)
        if len(eod_history) >= BOOST_DEMOTION_PROPOSAL_PERSIST_DAYS:
            candidates = _detect_boost_demotion_candidates(eod_history)
            print(f"[rule_proposer] prop_007: "
                  f"{len(candidates)} demotion candidate(s) "
                  f"with {BOOST_DEMOTION_PROPOSAL_PERSIST_DAYS}-day streak")
            new_demotion_proposals = _generate_boost_demotion_proposals(
                proposals, candidates)
            for p in new_demotion_proposals:
                proposals.append(p)
                new_count += 1
        else:
            print(f"[rule_proposer] prop_007: "
                  f"only {len(eod_history)} EOD history file(s) "
                  f"available; need "
                  f"{BOOST_DEMOTION_PROPOSAL_PERSIST_DAYS} for streak. "
                  f"Skipping demotion proposal generation.")
    except ImportError:
        pass

    # Build output
    pending_count = sum(1 for p in proposals if p.get('status') == 'pending')
    approved_count = sum(1 for p in proposals if p.get('status') == 'approved')
    rejected_count = sum(1 for p in proposals if p.get('status') == 'rejected')

    output = {
        'schema_version': SCHEMA_VERSION,
        'generated_at': datetime.utcnow().isoformat() + "Z",
        'source_patterns_file': PATTERNS_PATH,
        'source_patterns_count': len(patterns),
        'active_kill_rules_count': len(active_kills),
        'total_proposals': len(proposals),
        'pending_count': pending_count,
        'approved_count': approved_count,
        'rejected_count': rejected_count,
        'already_active_count': already_active_count,
        'thresholds': {
            'min_n_for_proposal': MIN_N_FOR_PROPOSAL,
            'min_edge_pp_warn': MIN_EDGE_PP,
            'min_edge_pp_kill': MIN_EDGE_PP_KILL
        },
        'proposals': proposals
    }

    _save_json(PROPOSED_RULES_PATH, output)

    print(f"[rule_proposer] Output written: {PROPOSED_RULES_PATH}")
    print(f"[rule_proposer] Summary:")
    print(f"  Total proposals: {len(proposals)}")
    print(f"  New this run: {new_count}")
    print(f"  Updated this run: {updated_count}")
    print(f"  Pending approval: {pending_count}")
    print(f"  Already active: {already_active_count}")
    print(f"  Approved: {approved_count}")
    print(f"  Rejected: {rejected_count}")

    return {
        'total': len(proposals),
        'pending': pending_count,
        'already_active': already_active_count,
        'approved': approved_count,
        'rejected': rejected_count,
        'new': new_count,
        'updated': updated_count
    }


def approve_proposal(proposal_id, approved_by='telegram_user'):
    """
    Approve a pending proposal and add it to mini_scanner_rules.json kill_patterns.
    Called by telegram_bot.py /approve_rule command.

    C-04 FIX: Returns dict (was tuple). Shape:
      {
        'success': bool,
        'action': str,           # 'kill' | 'warn'
        'target': str,           # human-readable "SIGNAL+sector"
        'message': str,          # full success message
        'kill_rule_id': str,     # new kill rule ID (on success)
        'error': str,            # error message (on failure)
      }
    """
    data = _load_json(PROPOSED_RULES_PATH, default={"proposals": []})
    proposals = data.get('proposals', [])

    # Find proposal
    target = None
    for p in proposals:
        if p.get('id') == proposal_id:
            target = p
            break

    if target is None:
        return {
            'success': False,
            'error': f"Proposal {proposal_id} not found",
        }

    if target.get('status') != 'pending':
        return {
            'success': False,
            'error': (
                f"Proposal {proposal_id} status is "
                f"'{target.get('status')}', only 'pending' "
                f"can be approved"),
        }

    if target.get('action') not in ('kill', 'warn', 'demote_boost'):
        return {
            'success': False,
            'error': (
                f"Proposal {proposal_id} action "
                f"'{target.get('action')}' not supported "
                f"for auto-approval"),
        }

    # prop_007: demote_boost branch — separate mutation path from
    # kill_pattern append. Locate boost_pattern by pattern_id, flip
    # active=False, write atomically via _save_json.
    if target.get('action') == 'demote_boost':
        return _approve_demote_boost(target, approved_by, data, proposals)

    # Add to mini_scanner_rules.json kill_patterns
    rules = _load_json(MINI_RULES_PATH, default={})
    if 'kill_patterns' not in rules:
        rules['kill_patterns'] = []

    # Build kill rule entry
    kill_id = f"kill_{proposal_id.replace('prop_', '')}"
    kill_entry = {
        'id': kill_id,
        'signal': target.get('target_signal'),
        'sector': target.get('target_sector'),
        'reason': f"Pattern miner: {target.get('evidence', {}).get('wr', 0)}% WR in {target.get('evidence', {}).get('n', 0)} trades",
        'added_date': datetime.utcnow().strftime('%Y-%m-%d'),
        'source': f'rule_proposer_{proposal_id}',
        'proposal_id': proposal_id
    }

    # Check duplicate
    already_exists = any(
        k.get('signal') == kill_entry['signal'] and
        k.get('sector') == kill_entry['sector']
        for k in rules['kill_patterns']
    )

    if not already_exists:
        rules['kill_patterns'].append(kill_entry)
        _save_json(MINI_RULES_PATH, rules)

    # Update proposal status
    target['status'] = 'approved'
    target['approved_date'] = datetime.utcnow().isoformat() + "Z"
    target['approved_by'] = approved_by
    target['kill_rule_id'] = kill_id
    data['proposals'] = proposals

    # Update counts
    data['pending_count'] = sum(1 for p in proposals if p.get('status') == 'pending')
    data['approved_count'] = sum(1 for p in proposals if p.get('status') == 'approved')

    _save_json(PROPOSED_RULES_PATH, data)

    # Build human-readable target string
    sig = kill_entry['signal'] or ''
    sec = kill_entry['sector'] or ''
    target_str = sig + (f"+{sec}" if sec else '')

    msg = (
        f"✅ Rule {proposal_id} approved\n"
        f"Now blocking: {target_str}\n"
        f"Based on: {target.get('evidence', {}).get('wr', 0)}% WR "
        f"in {target.get('evidence', {}).get('n', 0)} trades"
    )

    return {
        'success':      True,
        'action':       target.get('action', 'kill'),
        'target':       target_str,
        'message':      msg,
        'kill_rule_id': kill_id,
    }


def _approve_demote_boost(target, approved_by, data, proposals):
    """prop_007 demotion mutation: flip active=False on the
    referenced boost_pattern in mini_scanner_rules.json. Atomic write
    via _save_json (same primitive as kill_pattern append).

    Stale path (S4): if pattern_id not found in current
    mini_scanner_rules.boost_patterns, mark proposal status='stale',
    return error to caller, no mutation. The 'stale' status means the
    pattern was demoted/removed by some other means between proposal
    and approval; the proposal is preserved for audit but cannot apply.
    """
    pattern_id = target.get('pattern_id')
    rules = _load_json(MINI_RULES_PATH, default={})
    boost_patterns = rules.get('boost_patterns', [])

    # Locate by id
    found_idx = None
    for i, bp in enumerate(boost_patterns):
        if bp.get('id') == pattern_id:
            found_idx = i
            break

    if found_idx is None:
        target['status'] = 'stale'
        target['last_updated'] = datetime.utcnow().isoformat() + "Z"
        # Recompute summary counts after status change
        data['pending_count'] = sum(
            1 for p in proposals if p.get('status') == 'pending')
        _save_json(PROPOSED_RULES_PATH, data)
        return {
            'success': False,
            'error': (
                f"Proposal {target.get('id')}: boost_pattern "
                f"'{pattern_id}' not found in mini_scanner_rules.json. "
                f"Status flipped to 'stale'."),
        }

    # Apply demotion: flip active=False
    bp = boost_patterns[found_idx]
    if bp.get('active') is False:
        # Already demoted — soft success path. Still mark proposal
        # approved for audit. No re-write of mini_rules needed.
        target['status'] = 'approved'
        target['approved_date'] = datetime.utcnow().isoformat() + "Z"
        target['approved_by'] = approved_by
        target['last_updated'] = datetime.utcnow().isoformat() + "Z"
        data['pending_count'] = sum(
            1 for p in proposals if p.get('status') == 'pending')
        data['approved_count'] = sum(
            1 for p in proposals if p.get('status') == 'approved')
        _save_json(PROPOSED_RULES_PATH, data)
        return {
            'success': True,
            'action':  'demote_boost',
            'target':  pattern_id,
            'message': (
                f"✅ Proposal {target.get('id')} approved\n"
                f"Boost pattern {pattern_id} already had "
                f"active=False; no change to mini_rules required."),
            'pattern_id': pattern_id,
        }

    # Per S3 lock: mutation flips ONLY active=False. Audit trail
    # lives in proposed_rules.json (proposal.id + approved_date +
    # approved_by + pattern_id). Do NOT add demoted_date or
    # demoted_by_proposal fields to mini_scanner_rules.json — that
    # bloats the rules file with per-pattern decision metadata.
    # "When was win_001 demoted" is answered by:
    #   grep pattern_id=win_001 + action=demote_boost +
    #   status=approved in proposed_rules.json
    bp['active'] = False
    _save_json(MINI_RULES_PATH, rules)

    # Update proposal status
    target['status'] = 'approved'
    target['approved_date'] = datetime.utcnow().isoformat() + "Z"
    target['approved_by'] = approved_by
    target['last_updated'] = datetime.utcnow().isoformat() + "Z"

    data['pending_count'] = sum(
        1 for p in proposals if p.get('status') == 'pending')
    data['approved_count'] = sum(
        1 for p in proposals if p.get('status') == 'approved')

    _save_json(PROPOSED_RULES_PATH, data)

    sig = bp.get('signal') or '?'
    sec = bp.get('sector') or 'any'
    reg = bp.get('regime') or 'any'
    msg = (
        f"✅ Proposal {target.get('id')} approved\n"
        f"Boost pattern demoted: {pattern_id} ({sig} × {sec} × {reg})\n"
        f"active flipped to False. Reversible by manual re-edit."
    )
    return {
        'success':    True,
        'action':     'demote_boost',
        'target':     pattern_id,
        'message':    msg,
        'pattern_id': pattern_id,
    }


def reject_proposal(proposal_id, reason='No reason given', rejected_by='telegram_user'):
    """
    Reject a pending proposal (keeps it in log but not applied).

    C-04 FIX: Returns dict (was tuple). Shape matches approve_proposal.
    """
    data = _load_json(PROPOSED_RULES_PATH, default={"proposals": []})
    proposals = data.get('proposals', [])

    target = None
    for p in proposals:
        if p.get('id') == proposal_id:
            target = p
            break

    if target is None:
        return {
            'success': False,
            'error':   f"Proposal {proposal_id} not found",
        }

    if target.get('status') != 'pending':
        return {
            'success': False,
            'error': (
                f"Proposal {proposal_id} already in status "
                f"'{target.get('status')}'"),
        }

    target['status'] = 'rejected'
    target['rejected_date'] = datetime.utcnow().isoformat() + "Z"
    target['rejected_reason'] = reason
    target['rejected_by'] = rejected_by

    data['pending_count'] = sum(1 for p in proposals if p.get('status') == 'pending')
    data['rejected_count'] = sum(1 for p in proposals if p.get('status') == 'rejected')

    _save_json(PROPOSED_RULES_PATH, data)

    return {
        'success': True,
        'action':  'reject',
        'target':  proposal_id,
        'message': f"❌ Proposal {proposal_id} rejected: {reason}",
    }


def get_pending_proposals():
    """Return list of pending proposals for Telegram report."""
    data = _load_json(PROPOSED_RULES_PATH, default={"proposals": []})
    return [p for p in data.get('proposals', []) if p.get('status') == 'pending']


if __name__ == "__main__":
    # Standalone execution
    result = generate_proposals()
    print(f"\n[rule_proposer] Done. {result}")
