"""
rule_proposer.py — Pattern-to-Rule Proposer

Purpose:
  Reads output/patterns.json (generated by pattern_miner)
  Finds validated/preliminary patterns with negative direction and high edge
  Writes output/proposed_rules.json with actionable proposals

  Proposals can be approved via Telegram /approve_rule <id> command,
  which updates data/mini_scanner_rules.json automatically.

Key rules:
  - Only surface patterns with edge >= 10pp AND n >= 10
  - Skip patterns already active in mini_scanner_rules.json kill_patterns
  - Mark previously approved proposals as "already_active" (not duplicated)
  - Status lifecycle: pending -> approved / rejected / already_active

Output schema:
  {
    "schema_version": 1,
    "generated_at": "...",
    "total_proposals": N,
    "pending_count": N,
    "proposals": [ {...} ]
  }

FIX C-02 (Apr 21 2026):
  Replaced bare-relative paths (PATTERNS_PATH / PROPOSED_RULES_PATH /
  MINI_RULES_PATH) with _HERE/_ROOT absolute paths matching the
  pattern used by every other scanner module. The relative paths
  resolved to scanner/output/ and scanner/data/ when main.py ran
  with cwd=scanner/ (as eod_master.yml step 7 does), causing all
  reads to miss and all writes to land in disposable locations.

FIX C-04 (Apr 21 2026):
  approve_proposal() and reject_proposal() now return dicts instead
  of (bool, str) tuples. telegram_bot._respond_approve_rule calls
  .get() on the result, which raised AttributeError on every call.
  New shape: {success, action, target, message, error, kill_rule_id}
"""

import json
import os
from datetime import datetime
from pathlib import Path

# ── PATHS (C-02 FIX: absolute paths via _HERE/_ROOT) ─────────
_HERE   = os.path.dirname(os.path.abspath(__file__))
_ROOT   = os.path.dirname(_HERE)
_OUTPUT = os.path.join(_ROOT, 'output')
_DATA   = os.path.join(_ROOT, 'data')

PATTERNS_PATH       = os.path.join(_OUTPUT, 'patterns.json')
PROPOSED_RULES_PATH = os.path.join(_OUTPUT, 'proposed_rules.json')
MINI_RULES_PATH     = os.path.join(_DATA,   'mini_scanner_rules.json')

SCHEMA_VERSION = 1

# Thresholds for promoting patterns to proposals
MIN_N_FOR_PROPOSAL = 10           # minimum sample size
MIN_EDGE_PP = 10                   # minimum edge (percentage points)
MIN_EDGE_PP_KILL = 15              # minimum edge for KILL (stricter)


def _load_json(path, default=None):
    """Load JSON file with safe fallback."""
    if not os.path.exists(path):
        return default
    try:
        with open(path, 'r') as f:
            return json.load(f)
    except (json.JSONDecodeError, FileNotFoundError):
        print(f"[rule_proposer] Warning: {path} corrupt, using default")
        return default


def _save_json(path, data):
    """Save JSON atomically."""
    # Ensure parent directory exists (defensive — should always exist)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp_path = path + ".tmp"
    with open(tmp_path, 'w') as f:
        json.dump(data, f, indent=2)
    os.replace(tmp_path, path)


def _get_active_kill_patterns():
    """Read current kill_patterns from mini_scanner_rules.json."""
    rules = _load_json(MINI_RULES_PATH, default={})
    return rules.get('kill_patterns', [])


def _pattern_matches_active_rule(pattern, active_kills):
    """Check if a pattern is already an active kill rule."""
    features = pattern.get('features', {})
    target_signal = features.get('signal')
    target_sector = features.get('sector')

    if not target_signal or not target_sector:
        return False

    for kill in active_kills:
        if (kill.get('signal') == target_signal and
                kill.get('sector') == target_sector):
            return True
    return False


def _load_existing_proposals():
    """Load existing proposed_rules.json to preserve history."""
    data = _load_json(PROPOSED_RULES_PATH, default={
        "schema_version": SCHEMA_VERSION,
        "proposals": []
    })
    return data.get('proposals', [])


def _generate_proposal_id(existing_proposals):
    """Generate next prop_XXX ID."""
    existing_ids = [
        p.get('id', '') for p in existing_proposals
        if p.get('id', '').startswith('prop_')
    ]
    max_num = 0
    for pid in existing_ids:
        try:
            num = int(pid.replace('prop_', ''))
            max_num = max(max_num, num)
        except ValueError:
            continue
    return f"prop_{str(max_num + 1).zfill(3)}"


def _find_matching_proposal(pattern_id, existing_proposals):
    """Check if a proposal for this pattern already exists."""
    for p in existing_proposals:
        if p.get('pattern_id') == pattern_id:
            return p
    return None


def _classify_action(pattern):
    """
    Decide what action this pattern should propose.

    - kill: n>=10, edge<=-15pp, direction=negative
    - warn: n>=10, edge<=-10pp, direction=negative
    - boost: n>=10, edge>=15pp, direction=positive (future use)
    """
    n = pattern.get('n_resolved', 0)
    edge = pattern.get('edge_pct', 0) or 0
    direction = pattern.get('direction', '')

    if n < MIN_N_FOR_PROPOSAL:
        return None

    if direction == 'negative':
        if edge <= -MIN_EDGE_PP_KILL:
            return 'kill'
        elif edge <= -MIN_EDGE_PP:
            return 'warn'

    # Positive direction boost patterns — not acted upon yet, Phase 4
    # elif direction == 'positive' and edge >= MIN_EDGE_PP_KILL:
    #     return 'boost'

    return None


def _build_proposal(pattern, existing_proposals, active_kills):
    """Convert a pattern into a proposal record."""
    action = _classify_action(pattern)
    if action is None:
        return None

    features = pattern.get('features', {})
    target_signal = features.get('signal')
    target_sector = features.get('sector')

    # Need at least signal OR sector feature to be actionable
    if not target_signal and not target_sector:
        return None

    pattern_id = pattern.get('id', '')

    # Check if proposal already exists for this pattern
    existing = _find_matching_proposal(pattern_id, existing_proposals)

    if existing:
        # Already proposed — update evidence with latest numbers, keep status
        existing['evidence'] = {
            'wr': pattern.get('wr', 0),
            'n': pattern.get('n_resolved', 0),
            'avg_pnl': pattern.get('avg_pnl', 0),
            'avg_mae': pattern.get('avg_mae', 0),
            'avg_mfe': pattern.get('avg_mfe', 0),
            'edge_pp': pattern.get('edge_pct', 0),
            'tier': pattern.get('tier', ''),
            'baseline_type': pattern.get('baseline_type', ''),
            'baseline_wr': pattern.get('baseline_wr', 0)
        }
        existing['last_updated'] = datetime.utcnow().isoformat() + "Z"

        # If this was pending and is now active in rules, mark it
        if existing.get('status') == 'pending' and _pattern_matches_active_rule(pattern, active_kills):
            existing['status'] = 'already_active'
            existing['approved_date'] = datetime.utcnow().isoformat() + "Z"
            existing['approved_by'] = 'auto_sync_kill_patterns'

        return existing

    # New proposal
    prop_id = _generate_proposal_id(existing_proposals)

    # Check if this matches an already-active kill rule (shipped manually tonight)
    if _pattern_matches_active_rule(pattern, active_kills):
        status = 'already_active'
    else:
        status = 'pending'

    proposal = {
        'id': prop_id,
        'pattern_id': pattern_id,
        'action': action,
        'target_signal': target_signal,
        'target_sector': target_sector,
        'evidence': {
            'wr': pattern.get('wr', 0),
            'n': pattern.get('n_resolved', 0),
            'avg_pnl': pattern.get('avg_pnl', 0),
            'avg_mae': pattern.get('avg_mae', 0),
            'avg_mfe': pattern.get('avg_mfe', 0),
            'edge_pp': pattern.get('edge_pct', 0),
            'tier': pattern.get('tier', ''),
            'baseline_type': pattern.get('baseline_type', ''),
            'baseline_wr': pattern.get('baseline_wr', 0)
        },
        'status': status,
        'proposed_date': datetime.utcnow().isoformat() + "Z",
        'approved_date': datetime.utcnow().isoformat() + "Z" if status == 'already_active' else None,
        'approved_by': 'auto_sync_kill_patterns' if status == 'already_active' else None,
        'rejected_date': None,
        'rejected_reason': None,
        'last_updated': datetime.utcnow().isoformat() + "Z",
        'insight': pattern.get('insight', '')
    }

    return proposal


def generate_proposals():
    """
    Main entry point.
    Reads patterns.json, generates proposals, writes proposed_rules.json.
    Returns summary dict.
    """
    print("[rule_proposer] Starting proposal generation...")
    print(f"[rule_proposer] PATTERNS_PATH       = {PATTERNS_PATH}")
    print(f"[rule_proposer] PROPOSED_RULES_PATH = {PROPOSED_RULES_PATH}")
    print(f"[rule_proposer] MINI_RULES_PATH     = {MINI_RULES_PATH}")

    # Load patterns
    patterns_data = _load_json(PATTERNS_PATH, default={"patterns": []})
    patterns = patterns_data.get('patterns', [])
    print(f"[rule_proposer] Loaded {len(patterns)} patterns from {PATTERNS_PATH}")

    if not patterns:
        print("[rule_proposer] No patterns found. Skipping.")
        return {"total": 0, "pending": 0, "already_active": 0}

    # Load existing proposals (preserve history)
    existing_proposals = _load_existing_proposals()
    print(f"[rule_proposer] Found {len(existing_proposals)} existing proposals")

    # Load active kill rules
    active_kills = _get_active_kill_patterns()
    print(f"[rule_proposer] Found {len(active_kills)} active kill rules")

    # Process each pattern
    proposals = []
    new_count = 0
    updated_count = 0
    already_active_count = 0

    for pattern in patterns:
        proposal = _build_proposal(pattern, proposals + existing_proposals, active_kills)
        if proposal is None:
            continue

        # Check if it's in existing (updated) or new
        matching = _find_matching_proposal(
            proposal.get('pattern_id'), existing_proposals
        )
        if matching:
            updated_count += 1
        else:
            new_count += 1

        if proposal.get('status') == 'already_active':
            already_active_count += 1

        proposals.append(proposal)

    # Preserve existing proposals that weren't in this pattern set (maybe pattern disappeared as data shifted)
    existing_ids_in_current = {p.get('pattern_id') for p in proposals}
    for old_prop in existing_proposals:
        if old_prop.get('pattern_id') not in existing_ids_in_current:
            # Pattern no longer appears in latest patterns.json — mark stale but keep
            old_prop['status_note'] = 'pattern_no_longer_surfaced'
            old_prop['last_updated'] = datetime.utcnow().isoformat() + "Z"
            proposals.append(old_prop)

    # Build output
    pending_count = sum(1 for p in proposals if p.get('status') == 'pending')
    approved_count = sum(1 for p in proposals if p.get('status') == 'approved')
    rejected_count = sum(1 for p in proposals if p.get('status') == 'rejected')

    output = {
        'schema_version': SCHEMA_VERSION,
        'generated_at': datetime.utcnow().isoformat() + "Z",
        'source_patterns_file': PATTERNS_PATH,
        'source_patterns_count': len(patterns),
        'active_kill_rules_count': len(active_kills),
        'total_proposals': len(proposals),
        'pending_count': pending_count,
        'approved_count': approved_count,
        'rejected_count': rejected_count,
        'already_active_count': already_active_count,
        'thresholds': {
            'min_n_for_proposal': MIN_N_FOR_PROPOSAL,
            'min_edge_pp_warn': MIN_EDGE_PP,
            'min_edge_pp_kill': MIN_EDGE_PP_KILL
        },
        'proposals': proposals
    }

    _save_json(PROPOSED_RULES_PATH, output)

    print(f"[rule_proposer] Output written: {PROPOSED_RULES_PATH}")
    print(f"[rule_proposer] Summary:")
    print(f"  Total proposals: {len(proposals)}")
    print(f"  New this run: {new_count}")
    print(f"  Updated this run: {updated_count}")
    print(f"  Pending approval: {pending_count}")
    print(f"  Already active: {already_active_count}")
    print(f"  Approved: {approved_count}")
    print(f"  Rejected: {rejected_count}")

    return {
        'total': len(proposals),
        'pending': pending_count,
        'already_active': already_active_count,
        'approved': approved_count,
        'rejected': rejected_count,
        'new': new_count,
        'updated': updated_count
    }


def approve_proposal(proposal_id, approved_by='telegram_user'):
    """
    Approve a pending proposal and add it to mini_scanner_rules.json kill_patterns.
    Called by telegram_bot.py /approve_rule command.

    C-04 FIX: Returns dict (was tuple). Shape:
      {
        'success': bool,
        'action': str,           # 'kill' | 'warn'
        'target': str,           # human-readable "SIGNAL+sector"
        'message': str,          # full success message
        'kill_rule_id': str,     # new kill rule ID (on success)
        'error': str,            # error message (on failure)
      }
    """
    data = _load_json(PROPOSED_RULES_PATH, default={"proposals": []})
    proposals = data.get('proposals', [])

    # Find proposal
    target = None
    for p in proposals:
        if p.get('id') == proposal_id:
            target = p
            break

    if target is None:
        return {
            'success': False,
            'error': f"Proposal {proposal_id} not found",
        }

    if target.get('status') != 'pending':
        return {
            'success': False,
            'error': (
                f"Proposal {proposal_id} status is "
                f"'{target.get('status')}', only 'pending' "
                f"can be approved"),
        }

    if target.get('action') not in ('kill', 'warn'):
        return {
            'success': False,
            'error': (
                f"Proposal {proposal_id} action "
                f"'{target.get('action')}' not supported "
                f"for auto-approval"),
        }

    # Add to mini_scanner_rules.json kill_patterns
    rules = _load_json(MINI_RULES_PATH, default={})
    if 'kill_patterns' not in rules:
        rules['kill_patterns'] = []

    # Build kill rule entry
    kill_id = f"kill_{proposal_id.replace('prop_', '')}"
    kill_entry = {
        'id': kill_id,
        'signal': target.get('target_signal'),
        'sector': target.get('target_sector'),
        'reason': f"Pattern miner: {target.get('evidence', {}).get('wr', 0)}% WR in {target.get('evidence', {}).get('n', 0)} trades",
        'added_date': datetime.utcnow().strftime('%Y-%m-%d'),
        'source': f'rule_proposer_{proposal_id}',
        'proposal_id': proposal_id
    }

    # Check duplicate
    already_exists = any(
        k.get('signal') == kill_entry['signal'] and
        k.get('sector') == kill_entry['sector']
        for k in rules['kill_patterns']
    )

    if not already_exists:
        rules['kill_patterns'].append(kill_entry)
        _save_json(MINI_RULES_PATH, rules)

    # Update proposal status
    target['status'] = 'approved'
    target['approved_date'] = datetime.utcnow().isoformat() + "Z"
    target['approved_by'] = approved_by
    target['kill_rule_id'] = kill_id
    data['proposals'] = proposals

    # Update counts
    data['pending_count'] = sum(1 for p in proposals if p.get('status') == 'pending')
    data['approved_count'] = sum(1 for p in proposals if p.get('status') == 'approved')

    _save_json(PROPOSED_RULES_PATH, data)

    # Build human-readable target string
    sig = kill_entry['signal'] or ''
    sec = kill_entry['sector'] or ''
    target_str = sig + (f"+{sec}" if sec else '')

    msg = (
        f"✅ Rule {proposal_id} approved\n"
        f"Now blocking: {target_str}\n"
        f"Based on: {target.get('evidence', {}).get('wr', 0)}% WR "
        f"in {target.get('evidence', {}).get('n', 0)} trades"
    )

    return {
        'success':      True,
        'action':       target.get('action', 'kill'),
        'target':       target_str,
        'message':      msg,
        'kill_rule_id': kill_id,
    }


def reject_proposal(proposal_id, reason='No reason given', rejected_by='telegram_user'):
    """
    Reject a pending proposal (keeps it in log but not applied).

    C-04 FIX: Returns dict (was tuple). Shape matches approve_proposal.
    """
    data = _load_json(PROPOSED_RULES_PATH, default={"proposals": []})
    proposals = data.get('proposals', [])

    target = None
    for p in proposals:
        if p.get('id') == proposal_id:
            target = p
            break

    if target is None:
        return {
            'success': False,
            'error':   f"Proposal {proposal_id} not found",
        }

    if target.get('status') != 'pending':
        return {
            'success': False,
            'error': (
                f"Proposal {proposal_id} already in status "
                f"'{target.get('status')}'"),
        }

    target['status'] = 'rejected'
    target['rejected_date'] = datetime.utcnow().isoformat() + "Z"
    target['rejected_reason'] = reason
    target['rejected_by'] = rejected_by

    data['pending_count'] = sum(1 for p in proposals if p.get('status') == 'pending')
    data['rejected_count'] = sum(1 for p in proposals if p.get('status') == 'rejected')

    _save_json(PROPOSED_RULES_PATH, data)

    return {
        'success': True,
        'action':  'reject',
        'target':  proposal_id,
        'message': f"❌ Proposal {proposal_id} rejected: {reason}",
    }


def get_pending_proposals():
    """Return list of pending proposals for Telegram report."""
    data = _load_json(PROPOSED_RULES_PATH, default={"proposals": []})
    return [p for p in data.get('proposals', []) if p.get('status') == 'pending']


if __name__ == "__main__":
    # Standalone execution
    result = generate_proposals()
    print(f"\n[rule_proposer] Done. {result}")
