"""
postopen — L2 (POST_OPEN) bridge composer.

Run at 09:40 IST after open_validator (09:32) writes open_prices.json.
Reads truth files + L1 history file, evaluates each signal against the
actual market open, recomputes R:R + re-runs bucket assignment, writes
a new POST_OPEN bridge_state.json. Telegram brief gets generated by a
separate workflow that reads bridge_state.json — and only fires when
something material changed (gap_breach OR bucket_change).

Resilient: per-signal errors logged but don't kill compose. Top-level
error catches catastrophic failures and writes emergency_state.

L1 SDRs are read from output/bridge_state_history/{date}_PRE_MARKET.json
(immutable, written by state_writer). L2 produces NEW POST_OPEN SDRs
with bucket_changed/previous_bucket fields populated when L1's call
no longer holds.

See doc/bridge_design_v1.md §3 (POST_OPEN day-flow), §13 (workflow),
§12.2 (Telegram template).
"""

import json
import os
import time
from datetime import datetime, timezone
from typing import Optional
from zoneinfo import ZoneInfo


# Helpers shared with L1 — imported from premarket.py to avoid duplication.
# If this list grows past ~12 imports, refactor to
# scanner/bridge/composers/_common.py.
from scanner.bridge.composers.premarket import (
    _to_bridge_signal,
    _strip_ns_suffix,
    _infer_direction,
    _today_ist,
    _now_iso,
    _count_buckets,
    _build_trade_plan,
    _build_gap_caveat,
    _build_contra_block,
    _build_basic_alerts,
    _build_summary,
    _build_audit,
)

from scanner.bridge.composers import _history_reader

from scanner.bridge.core import (
    bucket_engine,
    display_hints,
    error_handler,
    evidence_collector,
    state_writer,
    upstream_health,
)
from scanner.bridge.core.sdr import SDR
from scanner.bridge.queries import q_open_positions, q_signal_today
from scanner.bridge.rules.thresholds import (
    BRIDGE_STATE_SCHEMA_VERSION,
)


_PHASE = "POST_OPEN"
_BRIDGE_VERSION = "1.0.0"
_IST = ZoneInfo("Asia/Kolkata")

_BANNER_COLOR = {
    "OK":       "green",
    "DEGRADED": "orange",
    "ERROR":    "red",
}

_FORCE_SKIP_GATE = "L2_GAP_INVALID"


# =====================================================================
# Public entry point
# =====================================================================

def compose(market_date: Optional[str] = None,
            output_dir: str = "output",
            data_dir: str = "data") -> dict:
    """Run the full L2 POST_OPEN compose. Always returns a summary
    dict; never raises. On FATAL error, writes emergency state and
    returns phase_status=ERROR.

    L2 summary extends L1's with:
        should_send_telegram      — fire conditional Telegram?
        bucket_changes            — count of signals where L1≠L2 bucket
        gap_breaches              — count of signals with gap_severity=severe
        l1_reference_available    — was L1 history file found?
    """
    start_time = time.monotonic()

    try:
        return _compose_unsafe(
            start_time, market_date, output_dir, data_dir)
    except Exception as e:
        md = market_date or _today_ist()
        emergency = error_handler.build_emergency_state(
            phase=_PHASE,
            market_date=md,
            error_summary=(
                f"compose crashed: {type(e).__name__}: {e}"
            ),
        )
        try:
            state_writer.write_state(emergency, output_dir=output_dir)
        except Exception:
            pass

        return {
            "phase":                   _PHASE,
            "phase_status":            "ERROR",
            "market_date":             md,
            "signals_count":           0,
            "buckets":                 {"TAKE_FULL": 0, "TAKE_SMALL": 0,
                                        "WATCH": 0, "SKIP": 0},
            "open_positions_count":    0,
            "alerts_count":            1,
            "errors_logged":           len(error_handler.get_error_log()),
            "state_file_written":      "",
            "duration_ms":             int((time.monotonic() - start_time) * 1000),
            "should_send_telegram":    False,
            "bucket_changes":          0,
            "gap_breaches":            0,
            "l1_reference_available":  False,
            "error":                   f"{type(e).__name__}: {e}",
        }


def _compose_unsafe(start_time: float,
                    market_date: Optional[str],
                    output_dir: str,
                    data_dir: str) -> dict:
    """Main compose flow. Wrapped by compose() for catastrophic safety."""
    error_handler.reset_error_log()

    if market_date is None:
        market_date = _today_ist()

    # Step 1: Load truth files (ONCE) + open_prices.json (L2-specific)
    truth_files = evidence_collector.load_truth_files(
        output_dir=output_dir, data_dir=data_dir)
    truth_files["open_prices"] = _load_open_prices(output_dir)

    # Step 2: Read L1 reference (immutable, dated history file)
    l1_ref = _history_reader.read_l1_sdrs(
        market_date, output_dir=output_dir)

    # Step 3: Today's PENDING signals (same source as L1)
    today_signals = q_signal_today.run(
        truth_files.get("signal_history", {}),
        market_date=market_date,
    ) or []

    # Step 4: Per-signal compose. Track bucket_changes + gap_breaches inline.
    sdrs: list = []
    bucket_changes = 0
    gap_breaches = 0
    for signal in today_signals:
        if not isinstance(signal, dict):
            continue
        sig_id = signal.get("id") or "unknown"
        sdr = error_handler.safe_run(
            _process_one_signal,
            signal, truth_files, l1_ref, market_date,
            severity="WARNING",
            context=f"compose_signal:{sig_id}",
        )
        if sdr is None:
            continue
        sdrs.append(sdr)
        if sdr.bucket_changed:
            bucket_changes += 1
        gap_eval = (sdr.evidence or {}).get("gap_evaluation")
        if isinstance(gap_eval, dict) and \
                gap_eval.get("gap_severity") == "severe":
            gap_breaches += 1

    # Step 5: Open positions (same as L1)
    open_positions = q_open_positions.run(
        truth_files.get("signal_history", {}),
        market_date=market_date,
    ) or []

    # Step 6: Contra block (same as L1)
    contra_block = _build_contra_block(truth_files)

    # Step 7: Upstream health + alerts (same as L1)
    upstream = upstream_health.get_upstream_health(
        output_dir=output_dir, market_date=market_date)
    alerts = _build_basic_alerts(upstream)

    # Step 8: Phase status from logged errors
    phase_status = error_handler.compute_phase_status(default_status="OK")

    # Step 9: Decide Telegram trigger
    should_send_telegram = (bucket_changes > 0 or gap_breaches > 0)

    # Step 10: Banner counts
    validated_count = len(sdrs) - bucket_changes
    reclassified_count = bucket_changes

    # Step 11: Assemble state
    state = {
        "schema_version":  BRIDGE_STATE_SCHEMA_VERSION,
        "phase":           _PHASE,
        "phase_status":    phase_status,
        "phase_timestamp": _now_iso(),
        "market_date":     market_date,
        "banner":          _build_l2_banner(
            phase_status, validated_count, reclassified_count),
        "summary":         _build_summary(sdrs, open_positions),
        "signals":         [sdr.to_dict() for sdr in sdrs],
        "open_positions":  open_positions,
        "contra":          contra_block,
        "alerts":          alerts,
        "self_queries":    [],   # Wave 5
        "upstream_health": upstream,
        "audit":           _build_audit(
            start_time, today_signals, sdrs, truth_files),
    }

    # Step 12: Single write
    write_result = state_writer.write_state(state, output_dir=output_dir)

    # Step 13: Summary
    return {
        "phase":                   _PHASE,
        "phase_status":            phase_status,
        "market_date":             market_date,
        "signals_count":           len(sdrs),
        "buckets":                 _count_buckets(sdrs),
        "open_positions_count":    len(open_positions),
        "alerts_count":            len(alerts),
        "errors_logged":           len(error_handler.get_error_log()),
        "state_file_written":      write_result["state_file"],
        "duration_ms":             int((time.monotonic() - start_time) * 1000),
        "should_send_telegram":    should_send_telegram,
        "bucket_changes":          bucket_changes,
        "gap_breaches":            gap_breaches,
        "l1_reference_available":  l1_ref.get("found", False),
    }


# =====================================================================
# Per-signal processing — safe_run wraps this
# =====================================================================

def _process_one_signal(signal: dict,
                        truth_files: dict,
                        l1_ref: dict,
                        market_date: str) -> SDR:
    """Build evidence, gap-evaluate, assign bucket (with optional L2
    override), compute bucket_changed vs L1, return POST_OPEN SDR."""
    bridge_signal = _to_bridge_signal(signal)

    evidence = evidence_collector.collect_evidence(
        bridge_signal, truth_files)
    queries_executed = evidence_collector.get_queries_executed_list()
    queries_failed = evidence_collector.get_queries_failed_list()

    gap_eval = evidence.get("gap_evaluation")

    # L2 override path: gap >3% adverse → force SKIP regardless of Gates
    if isinstance(gap_eval, dict) \
            and gap_eval.get("entry_still_valid") is False:
        bucket_result = _force_skip_invalid_entry(bridge_signal, gap_eval)
    else:
        # Inject updated R:R into bridge_signal so bucket_engine's
        # validity check sees the post-open math
        if isinstance(gap_eval, dict) and isinstance(
                gap_eval.get("rr_at_actual_open"), (int, float)):
            bridge_signal["rr"] = gap_eval["rr_at_actual_open"]
        bucket_result = bucket_engine.assign_bucket(
            bridge_signal, evidence)

    # Look up L1 SDR (signal_id == record id, stable across phases)
    l1_sdr = (l1_ref or {}).get(
        "sdrs_by_signal_id", {}).get(signal.get("id"))

    return _build_l2_sdr(
        bridge_signal, bucket_result, evidence, gap_eval,
        l1_sdr, market_date,
        queries_executed, queries_failed,
    )


# =====================================================================
# SDR construction (L2)
# =====================================================================

def _build_l2_sdr(signal: dict,
                  bucket_result: dict,
                  evidence: dict,
                  gap_eval: Optional[dict],
                  l1_sdr: Optional[dict],
                  market_date: str,
                  queries_executed: list,
                  queries_failed: list) -> SDR:
    """Construct POST_OPEN SDR. Mirrors premarket._build_sdr but with
    L2 trade_plan (actual_open, recomputed rr), L2 gap_caveat
    (evaluated_at_l2 + gap_outcome), and bucket_changed reasoning vs
    L1 reference."""
    sig_type = signal.get("signal") or signal.get("signal_type") or "?"
    raw_symbol = signal.get("symbol") or "?"
    symbol_clean = _strip_ns_suffix(raw_symbol)
    sector = signal.get("sector") or "?"
    regime = signal.get("regime") or "?"
    age = signal.get("age")
    if not isinstance(age, (int, float)):
        age = signal.get("age_days") or 0
    age = int(age)
    score = signal.get("score")
    direction = signal.get("direction") or _infer_direction(sig_type)

    sdr_id = (
        f"sdr_{market_date}_{_PHASE}_{symbol_clean}_{sig_type}"
    )
    signal_id = signal.get("id") or sdr_id

    trade_plan = _build_trade_plan_l2(signal, gap_eval)
    gap_caveat = _build_gap_caveat_l2(signal, direction, gap_eval)

    new_bucket = bucket_result.get("bucket", "SKIP")
    tier_label = bucket_result.get("tier_label")

    # Bucket-change reasoning vs L1
    l1_bucket = l1_sdr.get("bucket") if isinstance(l1_sdr, dict) else None
    if l1_bucket is None:
        bucket_changed = False
        previous_bucket = None
        bucket_change_reason = (
            "L1 reference unavailable, L2 standalone"
            if not isinstance(l1_sdr, dict)
            else None
        )
    elif l1_bucket != new_bucket:
        bucket_changed = True
        previous_bucket = l1_bucket
        bucket_change_reason = _bucket_change_reason(
            bucket_result, gap_eval, l1_bucket, new_bucket)
    else:
        bucket_changed = False
        previous_bucket = None
        bucket_change_reason = None

    display = display_hints.assemble_display_block(
        bucket=new_bucket,
        symbol=symbol_clean,
        signal_type=sig_type,
        sector=sector,
        regime=regime,
        score=int(score) if isinstance(score, (int, float)) else 0,
        tier_label=tier_label,
        is_changed_bucket=bucket_changed,
        show_in_main=(new_bucket != "SKIP"),
        show_in_contra=(
            new_bucket == "SKIP"
            and bucket_result.get("kill_match") is not None
        ),
    )

    confidence_inputs = bucket_result.get("confidence_inputs", {}) or {}
    confidence_band = display_hints.get_confidence_band(
        bucket=new_bucket,
        exact_cohort_n=confidence_inputs.get("exact_cohort_n"),
        has_kill_match=bool(confidence_inputs.get("has_kill_match")),
    )
    learner_hooks = {
        "self_query_candidates": [],
        "confidence_band":       confidence_band,
        "uncertainty_dimensions": [],
        "gap_flags":             [],
    }

    audit = {
        "composed_by_version":     f"bridge_v{_BRIDGE_VERSION}",
        "compose_phase_timestamp": _now_iso(),
        "queries_executed":        list(queries_executed),
        "queries_failed":          list(queries_failed),
        "l1_signal_id_lookup":     {
            "found": isinstance(l1_sdr, dict),
            "l1_bucket": l1_bucket,
        },
    }

    return SDR(
        sdr_id=sdr_id,
        signal_id=signal_id,
        phase=_PHASE,
        phase_timestamp=_now_iso(),
        market_date=market_date,
        symbol=symbol_clean,
        signal_type=sig_type,
        direction=direction,
        sector=sector,
        regime=regime,
        age_days=age,
        trade_plan=trade_plan,
        bucket=new_bucket,
        bucket_reason_short=bucket_result.get("bucket_reason_short", ""),
        bucket_reason_long=bucket_result.get("bucket_reason_long", ""),
        gap_caveat=gap_caveat,
        evidence=evidence or {},
        display=display,
        audit=audit,
        is_sa_variant=bool(signal.get("is_sa", False)),
        origin=signal.get("parent_signal_id") or None,
        bucket_changed=bucket_changed,
        previous_bucket=previous_bucket,
        bucket_change_reason=bucket_change_reason,
        learner_hooks=learner_hooks,
    )


def _bucket_change_reason(bucket_result: dict,
                          gap_eval: Optional[dict],
                          l1_bucket: str,
                          new_bucket: str) -> str:
    """Compose a short rationale for why L2 reclassified."""
    if bucket_result.get("gate_fired") == _FORCE_SKIP_GATE:
        gap_pct = (gap_eval or {}).get("gap_pct")
        gap_pct_str = (
            f"{gap_pct:+.2f}%"
            if isinstance(gap_pct, (int, float))
            else "?%"
        )
        return (
            f"L1={l1_bucket} → L2={new_bucket}: "
            f"gap {gap_pct_str} adverse, entry invalidated"
        )
    # Otherwise: bucket_engine re-ran with updated rr/evidence and
    # arrived at a different gate.
    short = bucket_result.get("bucket_reason_short", "")
    return f"L1={l1_bucket} → L2={new_bucket}: {short}"


# =====================================================================
# L2 trade_plan + gap_caveat (delta from L1)
# =====================================================================

def _build_trade_plan_l2(signal: dict,
                         gap_eval: Optional[dict]) -> dict:
    """L1 trade_plan + actual_open + rr-at-actual-open."""
    plan = _build_trade_plan(signal)
    if not isinstance(gap_eval, dict):
        return plan

    actual_open = gap_eval.get("actual_open")
    if isinstance(actual_open, (int, float)):
        plan["actual_open"] = actual_open

    rr_at_actual_open = gap_eval.get("rr_at_actual_open")
    if isinstance(rr_at_actual_open, (int, float)):
        plan["rr"] = rr_at_actual_open

    return plan


def _build_gap_caveat_l2(signal: dict,
                         direction: str,
                         gap_eval: Optional[dict]) -> dict:
    """L1 gap_caveat structure + evaluated_at_l2=True + gap_outcome
    (OK/WARNING/SKIP/UNKNOWN/NOT_VALIDATED) + gap_outcome_message."""
    caveat = _build_gap_caveat(signal, direction)
    caveat["evaluated_at_l2"] = True

    if not isinstance(gap_eval, dict):
        caveat["gap_outcome"] = "NOT_VALIDATED"
        caveat["gap_outcome_message"] = (
            "Signal not in today's open validation batch "
            "(SA-derived or stale)."
        )
        return caveat

    caveat["gap_outcome"] = gap_eval.get("gap_status") or "UNKNOWN"
    caveat["gap_outcome_message"] = gap_eval.get("note") or ""
    return caveat


# =====================================================================
# L2 override path (gap >3% adverse → forced SKIP)
# =====================================================================

def _force_skip_invalid_entry(bridge_signal: dict,
                              gap_eval: dict) -> dict:
    """Returns a bucket_result dict shaped like
    bucket_engine.assign_bucket's output, but with bucket=SKIP and a
    fixed reason. Used when gap_eval.entry_still_valid is False."""
    gap_pct = gap_eval.get("gap_pct")
    gap_pct_str = (
        f"{gap_pct:+.2f}%"
        if isinstance(gap_pct, (int, float))
        else "?%"
    )
    severity = gap_eval.get("gap_severity") or "severe"

    short = "Gap >3% — entry invalidated"
    long = (
        f"Actual open gapped {gap_pct_str} from scan_price (severity: "
        f"{severity}), exceeding the 3% adverse threshold. L1 "
        f"recommendation no longer holds; L2 forces SKIP regardless "
        f"of cohort/boost evidence. {gap_eval.get('note', '')}"
    ).strip()

    return {
        "bucket":              "SKIP",
        "bucket_reason_short": short,
        "bucket_reason_long":  long,
        "gate_fired":          _FORCE_SKIP_GATE,
        "boost_match":         None,
        "kill_match":          None,
        "tier_label":          None,
        "confidence_inputs":   {
            "exact_cohort_n":  None,
            "has_kill_match":  False,
        },
    }


# =====================================================================
# L2 banner
# =====================================================================

def _build_l2_banner(phase_status: str,
                     validated_count: int,
                     reclassified_count: int) -> dict:
    """L2-specific banner per design doc + user spec.

    Edge cases:
      validated=0 AND reclassified=0 → "LIVE — no signals today"
      reclassified=0                 → "LIVE — N validated, no reclassifications"
      otherwise                      → "LIVE — N validated, M reclassified"

    DEGRADED prepends "(partial data)" annotation.
    """
    color = _BANNER_COLOR.get(phase_status, "neutral")

    if validated_count == 0 and reclassified_count == 0:
        core_text = "no signals today"
    elif reclassified_count == 0:
        core_text = (
            f"{validated_count} validated, no reclassifications"
        )
    else:
        core_text = (
            f"{validated_count} validated, "
            f"{reclassified_count} reclassified"
        )

    if phase_status == "DEGRADED":
        message = "LIVE — partial data"
        subtext = core_text
    elif phase_status == "ERROR":
        message = "Bridge degraded"
        subtext = "Check Actions logs for details"
    else:
        message = f"LIVE — {core_text}"
        subtext = "Validated against actual 09:15 open"

    return {
        "state":   phase_status,
        "color":   color,
        "message": message,
        "subtext": subtext,
    }


# =====================================================================
# L2 truth-file loader (open_prices.json — not in evidence_collector's
# standard set since L1 doesn't need it)
# =====================================================================

def _load_open_prices(output_dir: str) -> dict:
    """Load output/open_prices.json. Returns {} on missing/malformed.

    Wraps the read in error_handler.safe_run with severity=DEGRADED so
    a missing file shows up in queries_failed and downgrades the L2
    phase_status to DEGRADED rather than silently producing an empty
    result."""
    path = os.path.join(output_dir, "open_prices.json")

    def _do_load():
        if not os.path.exists(path):
            raise FileNotFoundError(path)
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    result = error_handler.safe_run(
        _do_load,
        severity="DEGRADED",
        context="load_open_prices",
    )
    if isinstance(result, dict):
        return result
    return {}
