"""
premarket — L1 (PRE_MARKET) bridge composer.

Run before NSE open at 8:55 IST. Reads truth files, iterates today's PENDING
signals from signal_history, builds SDRs via evidence_collector + bucket_engine,
writes bridge_state.json. Telegram brief gets generated by separate workflow
that reads bridge_state.json.

Idempotent: running compose twice the same day produces the same output.
Resilient: per-signal errors logged but don't kill compose. Top-level error
catches catastrophic failures and writes emergency_state.

See doc/bridge_design_v1.md §13 (composer pattern), §10 (bridge_state schema).
"""

import time
from datetime import datetime, timezone
from typing import Any, Optional
from zoneinfo import ZoneInfo

from scanner.bridge.core import (
    bucket_engine,
    display_hints,
    error_handler,
    evidence_collector,
    state_writer,
    upstream_health,
)
from scanner.bridge.core.sdr import SDR
from scanner.bridge.queries import q_open_positions, q_signal_today
from scanner.bridge.rules import watch_matcher
from scanner.bridge.rules.thresholds import (
    BRIDGE_STATE_SCHEMA_VERSION,
    CONTRA_BLOCK_SCHEMA_VERSION,
    GAP_CAVEAT_DIRECTION,
    GAP_CAVEAT_THRESHOLD_PCT,
)


_IST = ZoneInfo("Asia/Kolkata")
_BRIDGE_VERSION = "1.0.0"
_PHASE = "PRE_MARKET"

_BANNER_COLOR = {
    "OK":       "green",
    "DEGRADED": "orange",
    "ERROR":    "red",
}


# =====================================================================
# Public entry point
# =====================================================================

def compose(market_date: Optional[str] = None,
            output_dir: str = "output",
            data_dir: str = "data") -> dict:
    """Run the full L1 PRE_MARKET compose. Always returns a summary
    dict; never raises. On FATAL error, writes emergency state and
    returns phase_status=ERROR."""
    start_time = time.monotonic()

    try:
        return _compose_unsafe(
            start_time, market_date, output_dir, data_dir)
    except Exception as e:
        # Catastrophic failure — emergency state
        md = market_date or _today_ist()
        emergency = error_handler.build_emergency_state(
            phase=_PHASE,
            market_date=md,
            error_summary=(
                f"compose crashed: {type(e).__name__}: {e}"
            ),
        )
        try:
            state_writer.write_state(emergency, output_dir=output_dir)
        except Exception:
            pass  # if even emergency-write fails, give up

        return {
            "phase": _PHASE,
            "phase_status": "ERROR",
            "market_date": md,
            "signals_count": 0,
            "buckets": {"TAKE_FULL": 0, "TAKE_SMALL": 0,
                        "WATCH": 0, "SKIP": 0},
            "open_positions_count": 0,
            "alerts_count": 1,
            "errors_logged": len(error_handler.get_error_log()),
            "state_file_written": "",
            "duration_ms": int((time.monotonic() - start_time) * 1000),
            "error": f"{type(e).__name__}: {e}",
        }


def _compose_unsafe(start_time: float,
                    market_date: Optional[str],
                    output_dir: str,
                    data_dir: str) -> dict:
    """Main compose flow. Wrapped by compose() for catastrophic safety."""
    error_handler.reset_error_log()

    if market_date is None:
        market_date = _today_ist()

    # Step 1: Load truth files (ONCE)
    truth_files = evidence_collector.load_truth_files(
        output_dir=output_dir, data_dir=data_dir)

    # Step 2: Today's PENDING signals
    today_signals = q_signal_today.run(
        truth_files.get("signal_history", {}),
        market_date=market_date,
    ) or []

    # Step 3: Per-signal compose
    sdrs: list = []
    for signal in today_signals:
        if not isinstance(signal, dict):
            continue
        sig_id = signal.get("id") or "unknown"
        sdr = error_handler.safe_run(
            _process_one_signal,
            signal, truth_files, market_date,
            severity="WARNING",
            context=f"compose_signal:{sig_id}",
        )
        if sdr is not None:
            sdrs.append(sdr)

    # Step 4: Open positions (prior days)
    open_positions = q_open_positions.run(
        truth_files.get("signal_history", {}),
        market_date=market_date,
    ) or []

    # Step 5: Contra block
    contra_block = _build_contra_block(truth_files)

    # Step 6: Upstream health (also feeds alerts)
    upstream = upstream_health.get_upstream_health(
        output_dir=output_dir, market_date=market_date)

    # Step 7: Alerts (Wave 2 minimal — upstream health only)
    alerts = _build_basic_alerts(upstream)

    # Step 8: Phase status from logged errors
    phase_status = error_handler.compute_phase_status(default_status="OK")

    # Step 9: Assemble bridge_state
    state = {
        "schema_version":  BRIDGE_STATE_SCHEMA_VERSION,
        "phase":           _PHASE,
        "phase_status":    phase_status,
        "phase_timestamp": _now_iso(),
        "market_date":     market_date,
        "banner":          _build_banner(phase_status, len(sdrs)),
        "summary":         _build_summary(sdrs, open_positions),
        "signals":         [sdr.to_dict() for sdr in sdrs],
        "open_positions":  open_positions,
        "contra":          contra_block,
        "alerts":          alerts,
        "self_queries":    [],   # Wave 5
        "upstream_health": upstream,
        "audit":           _build_audit(
            start_time, today_signals, sdrs, truth_files),
    }

    # Step 10: Single write
    write_result = state_writer.write_state(state, output_dir=output_dir)

    # Step 11: Summary
    return {
        "phase":                 _PHASE,
        "phase_status":          phase_status,
        "market_date":           market_date,
        "signals_count":         len(sdrs),
        "buckets":               _count_buckets(sdrs),
        "open_positions_count":  len(open_positions),
        "alerts_count":          len(alerts),
        "errors_logged":         len(error_handler.get_error_log()),
        "state_file_written":    write_result["state_file"],
        "duration_ms":           int((time.monotonic() - start_time) * 1000),
    }


# =====================================================================
# Per-signal processing — safe_run wraps this
# =====================================================================

def _process_one_signal(signal: dict,
                        truth_files: dict,
                        market_date: str) -> SDR:
    """Build evidence, assign bucket, return an SDR. Raises on failure;
    caller wraps in safe_run."""
    # Translate canonical signal_history record → bridge-format signal
    # so bucket_engine / validity_checker / queries can read
    # signal_type / age_days / rr by their bridge names.
    bridge_signal = _to_bridge_signal(signal)

    evidence = evidence_collector.collect_evidence(
        bridge_signal, truth_files)
    queries_executed = evidence_collector.get_queries_executed_list()
    queries_failed = evidence_collector.get_queries_failed_list()

    # Watch-pattern check (informational; never affects bucket).
    # Read-only metadata layer — see scanner/bridge/rules/watch_matcher.py.
    watch_matches = watch_matcher.check_matches(
        bridge_signal,
        (truth_files.get("mini_scanner_rules") or {}).get(
            "watch_patterns", []),
    )
    if watch_matches:
        evidence["watch_warnings"] = watch_matches

    bucket_result = bucket_engine.assign_bucket(
        bridge_signal, evidence,
    )

    return _build_sdr(
        bridge_signal, bucket_result, evidence,
        market_date,
        queries_executed, queries_failed,
    )


def _to_bridge_signal(record: dict) -> dict:
    """Add bridge-naming aliases to a canonical signal_history record.

    Adds (without overwriting if already present):
      signal_type ← signal
      age_days    ← age
      rr          ← compute from entry/stop/target if absent
    """
    bridge = dict(record)

    if bridge.get("signal_type") is None:
        bridge["signal_type"] = record.get("signal")

    if bridge.get("age_days") is None:
        a = record.get("age")
        bridge["age_days"] = (
            int(a) if isinstance(a, (int, float)) else 0)

    if bridge.get("rr") is None:
        rr = (
            record.get("rr")
            or record.get("adjusted_rr")
            or _compute_rr(
                record.get("entry"),
                record.get("stop"),
                record.get("target_price") or record.get("target"),
                record.get("direction")
                    or _infer_direction(record.get("signal", "")),
            )
        )
        bridge["rr"] = rr

    return bridge


def _build_sdr(signal: dict,
               bucket_result: dict,
               evidence: dict,
               market_date: str,
               queries_executed: list,
               queries_failed: list) -> SDR:
    """Construct an SDR instance from a processed signal."""
    sig_type = signal.get("signal") or signal.get("signal_type") or "?"
    raw_symbol = signal.get("symbol") or "?"
    symbol_clean = _strip_ns_suffix(raw_symbol)
    sector = signal.get("sector") or "?"
    regime = signal.get("regime") or "?"
    age = signal.get("age")
    if not isinstance(age, (int, float)):
        age = signal.get("age_days") or 0
    age = int(age)
    score = signal.get("score")
    direction = signal.get("direction") or _infer_direction(sig_type)

    sdr_id = (
        f"sdr_{market_date}_{_PHASE}_{symbol_clean}_{sig_type}"
    )
    signal_id = signal.get("id") or sdr_id

    trade_plan = _build_trade_plan(signal)
    gap_caveat = _build_gap_caveat(signal, direction)

    bucket = bucket_result.get("bucket", "SKIP")
    tier_label = bucket_result.get("tier_label")
    bucket_changed = bool(bucket_result.get("bucket_changed", False))

    display = display_hints.assemble_display_block(
        bucket=bucket,
        symbol=symbol_clean,
        signal_type=sig_type,
        sector=sector,
        regime=regime,
        score=int(score) if isinstance(score, (int, float)) else 0,
        tier_label=tier_label,
        is_changed_bucket=bucket_changed,
        show_in_main=(bucket != "SKIP"),
        show_in_contra=(
            bucket == "SKIP"
            and bucket_result.get("kill_match") is not None
        ),
    )

    confidence_inputs = bucket_result.get("confidence_inputs", {}) or {}
    confidence_band = display_hints.get_confidence_band(
        bucket=bucket,
        exact_cohort_n=confidence_inputs.get("exact_cohort_n"),
        has_kill_match=bool(confidence_inputs.get("has_kill_match")),
    )
    learner_hooks = {
        "self_query_candidates": [],
        "confidence_band":       confidence_band,
        "uncertainty_dimensions": [],
        "gap_flags":             [],
    }

    audit = {
        "composed_by_version":         f"bridge_v{_BRIDGE_VERSION}",
        "compose_phase_timestamp":     _now_iso(),
        "queries_executed":            list(queries_executed),
        "queries_failed":              list(queries_failed),
    }

    return SDR(
        sdr_id=sdr_id,
        signal_id=signal_id,
        phase=_PHASE,
        phase_timestamp=_now_iso(),
        market_date=market_date,
        symbol=symbol_clean,
        signal_type=sig_type,
        direction=direction,
        sector=sector,
        regime=regime,
        age_days=age,
        trade_plan=trade_plan,
        bucket=bucket,
        bucket_reason_short=bucket_result.get("bucket_reason_short", ""),
        bucket_reason_long=bucket_result.get("bucket_reason_long", ""),
        gap_caveat=gap_caveat,
        evidence=evidence or {},
        display=display,
        audit=audit,
        is_sa_variant=bool(signal.get("is_sa", False)),
        origin=signal.get("parent_signal_id") or None,
        bucket_changed=bucket_changed,
        previous_bucket=bucket_result.get("previous_bucket"),
        bucket_change_reason=bucket_result.get("bucket_change_reason"),
        learner_hooks=learner_hooks,
    )


# =====================================================================
# State sub-block builders
# =====================================================================

def _build_trade_plan(signal: dict) -> dict:
    entry = signal.get("entry") or signal.get("scan_price")
    stop  = signal.get("stop")
    target = signal.get("target_price") or signal.get("target")
    rr = _compute_rr(entry, stop, target,
                     signal.get("direction") or "LONG")
    risk_per_share = (
        abs(entry - stop)
        if isinstance(entry, (int, float))
        and isinstance(stop, (int, float))
        else None
    )
    score = signal.get("score")

    return {
        "scan_price":      signal.get("scan_price"),
        "actual_open":     None,  # filled at L2
        "entry":           entry,
        "stop":            stop,
        "target":          target,
        "rr":              rr,
        "risk_per_share":  risk_per_share,
        "atr":             signal.get("atr"),
        "score":           score,
        "score_components": _score_components(signal),
    }


def _build_gap_caveat(signal: dict, direction: str) -> dict:
    """Pre-market gap caveat per design doc §4.1."""
    scan_price = signal.get("scan_price") or signal.get("entry")
    threshold_pct = GAP_CAVEAT_THRESHOLD_PCT
    if isinstance(scan_price, (int, float)) and direction == "LONG":
        absolute = round(
            scan_price * (1 + threshold_pct / 100.0), 2)
        instruction = (
            f"Place at 09:15 open. If actual open gaps > "
            f"{threshold_pct}% above scan_price (above ₹{absolute}), "
            f"reconsider entry — gap likely consumed expected upside."
        )
    elif isinstance(scan_price, (int, float)) and direction == "SHORT":
        absolute = round(
            scan_price * (1 - threshold_pct / 100.0), 2)
        instruction = (
            f"Place at 09:15 open. If actual open gaps > "
            f"{threshold_pct}% below scan_price (below ₹{absolute}), "
            f"reconsider entry — gap likely consumed expected downside."
        )
    else:
        absolute = None
        instruction = (
            f"Place at 09:15 open. Reconsider entry if open gaps "
            f"adversely > {threshold_pct}% from scan_price."
        )

    return {
        "applies":                  True,
        "threshold_pct":            threshold_pct,
        "direction":                GAP_CAVEAT_DIRECTION,
        "absolute_threshold_price": absolute,
        "instruction":              instruction,
        "evaluated_at_l2":          False,  # PRE_MARKET phase
        "gap_outcome":              None,
        "gap_outcome_message":      None,
    }


def _build_contra_block(truth_files: dict) -> dict:
    """Wave 2 minimal contra block: active kills + pending shadows."""
    rules = truth_files.get("mini_scanner_rules", {}) or {}
    contra = truth_files.get("contra_shadow", {}) or {}

    active_rules = []
    for k in rules.get("kill_patterns", []) or []:
        if not isinstance(k, dict):
            continue
        if k.get("active") is False:
            continue
        active_rules.append({
            "kill_id":       k.get("id"),
            "signal":        k.get("signal"),
            "sector":        k.get("sector"),
            "regime":        k.get("regime"),
            "added_date":    k.get("added_date"),
            "evidence":      k.get("evidence"),
        })

    pending_shadows = []
    for s in contra.get("shadows", []) or []:
        if not isinstance(s, dict):
            continue
        if s.get("outcome") is not None:
            continue
        pending_shadows.append({
            "id":                  s.get("id"),
            "kill_rule_id":        s.get("kill_rule_id"),
            "origin_signal_type":  s.get("origin_signal_type"),
            "symbol":              s.get("symbol"),
            "sector":              s.get("sector"),
            "regime":              s.get("regime"),
            "date":                s.get("date"),
        })

    return {
        "schema_version":     CONTRA_BLOCK_SCHEMA_VERSION,
        "active_rules":       active_rules,
        "pending_shadows":    pending_shadows,
        "recent_resolutions": [],   # Wave 2: empty; populated in Wave 4
        "alerts_this_cycle":  [],
    }


def _build_basic_alerts(upstream: dict) -> list:
    """Wave 2 alerts = upstream-health degraded modules only."""
    alerts: list = []
    if not isinstance(upstream, dict):
        return alerts

    for module, status in upstream.items():
        if module.startswith("_"):
            continue
        if status == "error":
            alerts.append({
                "type":     "upstream_error",
                "severity": "critical",
                "message":  f"Upstream module {module} reports error",
                "evidence": {"module": module, "status": status},
            })
        elif status == "warn":
            alerts.append({
                "type":     "upstream_warn",
                "severity": "warning",
                "message":  f"Upstream module {module} reports warn",
                "evidence": {"module": module, "status": status},
            })
        elif status == "stale":
            alerts.append({
                "type":     "upstream_stale",
                "severity": "warning",
                "message":  f"Upstream module {module} report is stale",
                "evidence": {"module": module, "status": status},
            })
    return alerts


def _build_banner(phase_status: str, signal_count: int) -> dict:
    color = _BANNER_COLOR.get(phase_status, "neutral")
    state_label = phase_status

    if phase_status == "OK":
        message = "PROVISIONAL — validated at 09:30"
        subtext = (
            f"{signal_count} signals composed for review"
            if signal_count
            else "No new signals today"
        )
    elif phase_status == "DEGRADED":
        n_warn = sum(
            1 for e in error_handler.get_error_log()
            if e["severity"] in ("WARNING", "DEGRADED")
        )
        message = "PROVISIONAL — partial data"
        subtext = (
            f"{signal_count} signals composed; "
            f"{n_warn} warnings logged"
        )
    else:
        message = "Bridge degraded"
        subtext = "Check Actions logs for details"

    return {
        "state":   state_label,
        "color":   color,
        "message": message,
        "subtext": subtext,
    }


def _build_summary(sdrs: list, open_positions: list) -> dict:
    return {
        "total_signals_today":    len(sdrs),
        "buckets":                _count_buckets(sdrs),
        "open_positions_count":   len(open_positions),
    }


def _build_audit(start_time: float,
                 today_signals: list,
                 sdrs: list,
                 truth_files: dict) -> dict:
    log = error_handler.get_error_log()
    return {
        "bridge_version":         _BRIDGE_VERSION,
        "compose_started_at":     _iso_from_monotonic(start_time),
        "compose_completed_at":   _now_iso(),
        "compose_duration_ms":    int(
            (time.monotonic() - start_time) * 1000),
        "signal_count_input":     len(today_signals or []),
        "signal_count_output":    len(sdrs),
        "queries_total_distinct": _distinct_queries_count(log),
        "queries_failed":         [
            e["context"] for e in log
            if e.get("context", "").startswith("q_")
            or e.get("context", "").startswith("compose_signal:")
        ],
        "files_read":             sorted(truth_files.keys()),
        "warnings": [
            f"{e['severity']} {e['context']}: "
            f"{e.get('exception_type')}: {e.get('exception_message')}"
            for e in log
        ],
    }


# =====================================================================
# Helpers
# =====================================================================

def _count_buckets(sdrs: list) -> dict:
    out = {"TAKE_FULL": 0, "TAKE_SMALL": 0, "WATCH": 0, "SKIP": 0}
    for sdr in sdrs:
        b = getattr(sdr, "bucket", None)
        if b in out:
            out[b] += 1
    return out


def _strip_ns_suffix(symbol: str) -> str:
    if isinstance(symbol, str) and symbol.endswith(".NS"):
        return symbol[:-3]
    return symbol if isinstance(symbol, str) else "?"


def _infer_direction(sig_type: str) -> str:
    if isinstance(sig_type, str) and sig_type.upper().startswith("DOWN"):
        return "SHORT"
    return "LONG"


def _compute_rr(entry, stop, target, direction: str) -> Optional[float]:
    if not all(isinstance(v, (int, float)) for v in (entry, stop, target)):
        return None
    try:
        if direction == "SHORT":
            risk = stop - entry
            reward = entry - target
        else:
            risk = entry - stop
            reward = target - entry
        if risk <= 0:
            return None
        return round(reward / risk, 2)
    except Exception:
        return None


def _score_components(signal: dict) -> dict:
    """Wave 2 minimal — convert quality flags to 0/1 contributions."""
    return {
        "vol_confirm": 1 if signal.get("vol_confirm") else 0,
        "rs_strong":   1 if signal.get("rs_strong") else 0,
        "sec_leading": 1 if signal.get("sec_leading") else 0,
        "bear_bonus":  1 if signal.get("bear_bonus") else 0,
        "grade_bonus": 1 if signal.get("grade_A") else 0,
    }


def _distinct_queries_count(log: list) -> int:
    contexts = {e.get("context") for e in log
                if e.get("context", "").startswith("q_")}
    return len(contexts)


def _today_ist() -> str:
    return datetime.now(_IST).date().isoformat()


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _iso_from_monotonic(t: float) -> str:
    """Best-effort: return current ISO with delta noted."""
    return _now_iso()
